apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicaset
spec:
  replicas: 2
  selector:
    matchLabels:
      app: www
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: web
        image: httpd:2.4.46-alpine
        volumeMounts:
        - name: volume-web
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: volume-web
        hostPath: 
          path: /data/web
          type: DirectoryOrCreate
